import { FullConfig } from '@playwright/test';
import { FullResult } from '@playwright/test/reporter';
import * as fs from 'fs';
import * as path from 'path';
import { ConfigManager } from '../../config/ConfigManager';
import {
  reportToSlack,
  createSummaryText,
  saveTestResultsToFile,
  calculateTestStatistics
} from '../../utils/reportingUtils';
import { AzureBlobUploader } from '../../utils/reporting/azure';
import { PlaywrightSlackReportSender, PlaywrightTestSummary } from '../../utils/reporting/slack';
import { PSReportInfo } from '../../utils/reporting/ps-report-info';
import { PSTcmResultStatistics } from '../../utils/reporting/ps-tcm-statistics';

/**
 * Global teardown runs once after all tests
 * Processes test results and sends reports to configured channels (Slack, etc.)
 *
 * Enhanced Features:
 * - Custom report processing with TCM grouping
 * - PowerSchool-style statistics
 * - Azure Blob Storage upload for report sharing
 * - Enhanced Slack notifications with report links
 * - JIRA/Zephyr integration support
 *
 * Uses ConfigManager as the single source of truth for all configuration.
 * Slack integration is enabled when SLACK_ENABLED=true and SLACK_WEBHOOK_URL is set.
 */
async function globalTeardown(config: FullConfig): Promise<void> {
  const configManager = ConfigManager.getInstance();

  // Skip reporting if we're in dry run mode
  if (configManager.isDryRunEnabled()) {
    console.log('Dry run mode enabled, skipping global teardown reporting');
    return;
  }

  console.log('\n╔══════════════════════════════════════════════════════════╗');
  console.log('║          GLOBAL TEARDOWN - PROCESSING RESULTS            ║');
  console.log('╚══════════════════════════════════════════════════════════╝\n');

  // Get the run folder from environment variable (set by playwright.config.ts and custom reporter)
  const runFolder = process.env.PLAYWRIGHT_RUN_FOLDER;
  
  // Determine which results file to use
  let resultsPath: string;
  let customReportPath: string | undefined;
  
  if (runFolder && fs.existsSync(runFolder)) {
    resultsPath = path.join(runFolder, 'test-results.json');
    customReportPath = path.join(runFolder, 'report.json');
  } else {
    // Fallback to legacy location
    resultsPath = path.join(__dirname, '../../reports/test-results.json');
  }
  
  // Try to load custom report first (generated by custom-reporter.ts)
  let customReport: any = null;
  if (customReportPath && fs.existsSync(customReportPath)) {
    try {
      customReport = JSON.parse(fs.readFileSync(customReportPath, 'utf8'));
      console.log('✓ Loaded custom report from:', customReportPath);
    } catch (error) {
      console.warn('⚠ Could not load custom report:', error);
    }
  }
  
  if (fs.existsSync(resultsPath) || customReport) {
    try {
      let stats;
      let fullResult: FullResult;
      let reportInfo: PSReportInfo;
      let psStatistics: PSTcmResultStatistics | undefined;
      
      if (customReport) {
        // Use data from custom reporter
        stats = customReport.summary || calculateTestStatisticsFromCustomReport(customReport);
        reportInfo = PSReportInfo.fromConfig(
          customReport.reportInfo?.startTimestamp || Date.now(),
          customReport.reportInfo?.endTimestamp || Date.now()
        );
        
        // Create PS statistics from custom report
        if (customReport.summary?.psStatistics) {
          psStatistics = new PSTcmResultStatistics(
            customReport.summary.psStatistics.counts.pass,
            customReport.summary.psStatistics.counts.passCaution,
            customReport.summary.psStatistics.counts.failure,
            customReport.summary.psStatistics.counts.appbug,
            customReport.summary.psStatistics.counts.repair,
            customReport.summary.psStatistics.counts.skipped
          );
        }
        
        fullResult = {
          status: stats.failed > 0 ? 'failed' : 'passed',
          startTime: new Date(customReport.reportInfo?.startTimestamp || Date.now()),
          duration: customReport.summary?.duration || 0
        } as FullResult;
        
      } else {
        // Fallback to legacy results processing
        const resultsJson = fs.readFileSync(resultsPath, 'utf8');
        const results = JSON.parse(resultsJson);
        
        stats = calculateTestStatistics({
          ...results,
          status: 'passed',
          startTime: results.startTime || new Date(),
          duration: results.duration || 0
        } as FullResult);
        
        reportInfo = PSReportInfo.fromConfig(
          results.startTime ? new Date(results.startTime).getTime() : Date.now(),
          Date.now()
        );
        
        fullResult = {
          ...results,
          status: stats.failedTests > 0 ? 'failed' : 'passed',
          startTime: results.startTime || new Date(),
          duration: results.duration || 0
        } as FullResult;
      }
      
      // Print summary to console
      console.log(createSummaryText(fullResult));
      
      // Save detailed results to file with timestamp
      saveTestResultsToFile(fullResult);
      
      // Upload reports to Azure if configured
      let azureReportUrl: string | undefined;
      const azureUploader = new AzureBlobUploader();
      
      if (azureUploader.isConfigured() && runFolder) {
        console.log('\n📤 Uploading reports to Azure...');
        const uploadResult = await azureUploader.uploadPlaywrightReport(runFolder);
        if (uploadResult.success) {
          azureReportUrl = uploadResult.url;
          console.log(`✓ Reports uploaded to: ${azureReportUrl}`);
        } else {
          console.warn(`⚠ Azure upload failed: ${uploadResult.error}`);
        }
      }
      
      // Send results to Slack if enabled (using enhanced reporter)
      const slackSettings = configManager.getSlackReportSettings();
      if (slackSettings.enabled) {
        console.log('\n📬 Sending Slack notification...');
        
        // Prepare test summary for Slack
        const testSummary: PlaywrightTestSummary = {
          total: customReport?.summary?.total || stats.totalTests || 0,
          passed: customReport?.summary?.passed || stats.passedTests || 0,
          failed: customReport?.summary?.failed || stats.failedTests || 0,
          skipped: customReport?.summary?.skipped || stats.skippedTests || 0,
          flaky: customReport?.summary?.flaky || stats.flakingTests || 0,
          duration: customReport?.summary?.duration || fullResult.duration || 0,
          startTime: reportInfo.startTimestamp,
          endTime: reportInfo.endTimestamp,
          reportInfo: reportInfo,
          psStatistics: psStatistics,
          tcmTotal: customReport?.summary?.tcmTotal,
          tcmPassed: customReport?.summary?.tcmPassed,
          tcmFailed: customReport?.summary?.tcmFailed,
          tcmSkipped: customReport?.summary?.tcmSkipped,
          tcmIntermittent: customReport?.summary?.tcmIntermittent
        };
        
        const slackSuccess = await PlaywrightSlackReportSender.sendTestReport(testSummary, azureReportUrl);
        if (slackSuccess) {
          console.log('✓ Slack notification sent');
        } else {
          console.warn('⚠ Slack notification failed');
        }
      } else {
        console.log('\n⏭ Slack reporting is disabled. Set SLACK_ENABLED=true to enable.');
      }
      
      // Final summary
      const totalTests = customReport?.summary?.total || stats.totalTests || 0;
      const passedTests = customReport?.summary?.passed || stats.passedTests || 0;
      const failedTests = customReport?.summary?.failed || stats.failedTests || 0;
      const skippedTests = customReport?.summary?.skipped || stats.skippedTests || 0;
      
      console.log(`\n✅ Test run complete. Total: ${totalTests}, Passed: ${passedTests}, Failed: ${failedTests}, Skipped: ${skippedTests}`);
      
      if (runFolder) {
        console.log(`📁 Reports available at: ${runFolder}`);
      }
      if (azureReportUrl) {
        console.log(`🌐 Online reports: ${azureReportUrl}`);
      }
      
    } catch (error) {
      console.error('Error processing test results:', error);
    }
  } else {
    console.log('No test results found at:', resultsPath);
    console.log('Note: Results may be in run-specific folder. Check playwright-report/ directory.');
  }
}

/**
 * Calculate test statistics from custom report format
 */
function calculateTestStatisticsFromCustomReport(customReport: any): {
  totalTests: number;
  passedTests: number;
  failedTests: number;
  skippedTests: number;
  flakingTests: number;
} {
  if (customReport.summary) {
    return {
      totalTests: customReport.summary.total || 0,
      passedTests: customReport.summary.passed || 0,
      failedTests: customReport.summary.failed || 0,
      skippedTests: customReport.summary.skipped || 0,
      flakingTests: customReport.summary.flaky || 0
    };
  }
  
  // Calculate from tests array if summary not available
  const tests = customReport.tests || [];
  return {
    totalTests: tests.length,
    passedTests: tests.filter((t: any) => t.status === 'passed').length,
    failedTests: tests.filter((t: any) => t.status === 'failed' || t.status === 'timedOut').length,
    skippedTests: tests.filter((t: any) => t.status === 'skipped').length,
    flakingTests: tests.filter((t: any) => t.isIntermittent).length
  };
}

export default globalTeardown;